apiVersion: mellanox.com/v1alpha1
kind: IPoIBNetwork
metadata:
  name: mlnx-0
  namespace: infiniblah
spec:
  networkNamespace: "infiniblah"
  master: "ibp82s0"
  ipam: |
    {
      "type": "whereabouts",
      "datastore": "kubernetes",
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig"
      },
      "range": "192.168.6.225/28",
      "log_file" : "/var/log/whereabouts.log",
      "log_level" : "info",
      "gateway": "192.168.6.1"
    }
